language: php
dist: xenial

jobs:
  include:
    - stage: syntax
      php: 5.6
      before_script: php --version
      script: find src -name "*.php" -print0 | xargs -0 -n1 php -l
    - stage: syntax
      php: 7.0
      before_script: php --version
      script: find src -name "*.php" -print0 | xargs -0 -n1 php -l
    - stage: syntax
      php: 7.1
      before_script: php --version
      script: find src -name "*.php" -print0 | xargs -0 -n1 php -l
    - stage: syntax
      php: 7.2
      before_script: php --version
      script: find src -name "*.php" -print0 | xargs -0 -n1 php -l

    - stage: apache
      php: 5.6
      before_script:
        - sudo chmod +x ci/apache.sh
        - sudo chmod +x ci/apache-test.sh
        - sudo ./ci/apache.sh
      script:
        - res=$(php src/test.php)
        - echo $res
        - res=$(php src/index.php)
        - echo $res
        - res=$(curl http://127.0.0.1/src/test.php)
        - echo $res
        - res=$(curl http://127.0.0.1/src/index.php)
        - echo $res
    - stage: apache
      php: 7.0
      before_script:
        - sudo chmod +x ci/apache.sh
        - sudo chmod +x ci/apache-test.sh
        - sudo ./ci/apache.sh
      script:
        - res=$(php src/test.php)
        - echo $res
        - res=$(php src/index.php)
        - echo $res
        - res=$(curl http://127.0.0.1/src/test.php)
        - echo $res
        - res=$(curl http://127.0.0.1/src/index.php)
        - echo $res
    - stage: apache
      php: 7.1
      before_script:
        - sudo chmod +x ci/apache.sh
        - sudo chmod +x ci/apache-test.sh
        - sudo ./ci/apache.sh
      script:
        - res=$(php src/test.php)
        - echo $res
        - res=$(php src/index.php)
        - echo $res
        - res=$(curl http://127.0.0.1/src/test.php)
        - echo $res
        - res=$(curl http://127.0.0.1/src/index.php)
        - echo $res
    - stage: apache
      php: 7.2
      before_script:
        - sudo chmod +x ci/apache.sh
        - sudo chmod +x ci/apache-test.sh
        - sudo ./ci/apache.sh
      script:
        - res=$(php src/test.php)
        - echo $res
        - res=$(php src/index.php)
        - echo $res
        - res=$(curl http://127.0.0.1/src/test.php)
        - echo $res
        - res=$(curl http://127.0.0.1/src/index.php)
        - echo $res
